name: Deploy Frontend Production Server

on:
  workflow_dispatch:
    inputs:
      password:
        description: "Enter password to deploy"
        required: true

jobs:
  build-and-deploy:
    runs-on: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Validate Password
        id: password-check
        run: |
            if [ "$INPUT_PASSWORD" != "${{ secrets.PROD_WORKFLOW_PASSWORD }}" ]; then
              echo "Password does not match. Exiting workflow."
              exit 1
            fi
        env:
          INPUT_PASSWORD: ${{ github.event.inputs.password }}

      - name: Install dependencies
        run: npm install

      - name: Creating ENV
        run: cp ../../../../env/frontend-production.txt .env

      - name: Build Project
        run: npm run build

      - name: Restart PM2
        run: pm2 restart PROD-FRONTEND

      - name: Save Running Process
        run: pm2 save
